// Real-server browser smoke test using Chrome's CDP and Node built-ins.
// Build first: go build -o /private/tmp/minihub-threads ./cmd/minihub
// Run: node tests/threads-browser.mjs /private/tmp/minihub-threads
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'minihub-thread-smoke-'));
const reservation=net.createServer();await new Promise(r=>reservation.listen(0,'127.0.0.1',r));const port=reservation.address().port;await new Promise(r=>reservation.close(r));
const base=`http://127.0.0.1:${port}`, password='thread-test-password';
const app=spawn(process.argv[2]||'/private/tmp/minihub-threads',['-addr',`127.0.0.1:${port}`,'-data',path.join(temp,'data')],{cwd:temp,env:{...process.env,MINIHUB_ADMIN_PASSWORD:password},stdio:['ignore','pipe','pipe']});
let chrome,cdp;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
try{
 for(let i=0;i<100;i++){try{if((await fetch(base+'/login')).ok)break;}catch{}await pause(50);}
 async function login(user){const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:user,password})});assert.equal(r.status,200);return {cookie:r.headers.get('set-cookie').split(';')[0],csrf:(await r.json()).csrfToken};}
 const admin=await login('admin');
 async function api(session,url,method='GET',body){const r=await fetch(base+url,{method,headers:{Cookie:session.cookie,'X-CSRF-Token':session.csrf,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();if(!r.ok)throw Error(`${method} ${url}: ${r.status} ${text}`);return text?JSON.parse(text):null;}
 await api(admin,'/api/users','POST',{users:[{id:'bob',name:'鈴木',password,role:'user'}]});
 const bob=await login('bob');
 await api(admin,'/api/channels','POST',{id:'general',name:'全社連絡',type:'public'});
 await api(admin,'/api/channels','POST',{id:'other',name:'別チャンネル',type:'public'});
 await api(bob,'/api/channels/general/join','POST');
 const root=await api(admin,'/api/channels/general/messages','POST',{text:'来週の作業は火曜日でよいですか？'});
 for(let i=0;i<60;i++)await api(bob,`/api/channels/general/threads/${root.seq}/messages`,'POST',{text:i===0?'@admin 火曜日の14時に決まりました。':`返信 ${i+1}：<img src=x onerror=alert(1)> 詳細を確認します。`});
 const normal=await api(bob,'/api/channels/general/messages','POST',{text:'別の案件について共有します。'});
 await api(admin,`/api/channels/general/messages/${normal.seq}/reactions/ack`,'PUT');
 chrome=spawn(process.env.BROWSER_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-sandbox','--remote-debugging-port=0','--user-data-dir='+path.join(temp,'chrome'),'about:blank'],{stdio:['ignore','ignore','pipe']});
 const browserURL=await new Promise((resolve,reject)=>{let log='';const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),15000);chrome.stderr.on('data',b=>{log+=b;const match=log.match(/DevTools listening on (ws:\/\/\S+)/);if(match){clearTimeout(timer);resolve(match[1]);}});});
 const pages=await(await fetch('http://'+new URL(browserURL).host+'/json/list')).json();
 cdp=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>cdp.addEventListener('open',r,{once:true}));
 let seq=0;const pending=new Map(),errors=[],requests=[];
 cdp.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Network.requestWillBeSent')requests.push(m.params.request.url);});
 const send=(method,params={})=>new Promise(r=>{const id=++seq;pending.set(id,r);cdp.send(JSON.stringify({id,method,params}));});
 const run=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.result.exceptionDetails)throw Error(JSON.stringify(r.result.exceptionDetails));return r.result.result.value;};
 const wait=async(expression)=>{for(let i=0;i<150;i++){if(await run(expression))return;await pause(50);}throw Error('timeout: '+expression);};
 await send('Runtime.enable');await send('Network.enable');
 await send('Network.setCookie',{name:admin.cookie.split('=')[0],value:admin.cookie.split('=').slice(1).join('='),url:base});
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:base});await wait("typeof T !== 'undefined' && S.me && S.channels.length===2");
 assert.equal(await run("!document.querySelector('#threadUpdates') && $('join') === document.querySelector('.topicons').firstElementChild"),true);
 await run("$('threadTab').click()");
 assert.equal(await run("$('threadScopeChannel').disabled && $('threadScopeAll').getAttribute('aria-pressed') === 'true'"),true);
 await run("$('mentionTab').click()");
 await run("S.localNotifications=[{id:'test-notice',message:'テスト通知',type:'success',ts:new Date().toISOString(),seen:false}];saveLocalNotifications();renderNotificationCenter();$('noticeTab').click();window.confirm=()=>false;$('clearNotifications').click()");
 assert.equal(await run("S.localNotifications.length===1 && localStorage.getItem(notificationStorageKey())!==null"),true);
 await run("window.confirm=()=>true;$('clearNotifications').click()");
 assert.equal(await run("S.localNotifications.length===0 && localStorage.getItem(notificationStorageKey())===null && $('noticeList').textContent==='通知はありません' && $('clearNotifications').disabled"),true);
 await run("select('general')");await wait("S.msgs.length===2 && !S.initialLoading && !!document.querySelector('#messages [data-thread-root]')");
 assert.equal(requests.filter(p=>/\/threads\/\d+\/messages/.test(p)).length,0,'closed threads fetched bodies');
 assert.equal(await run("S.read.get('general').unreadCount"),1);
 assert.equal(await run("document.querySelector('#messages [data-thread-root]').textContent.includes('返信60件')"),true);
 assert.equal(await run(`(()=>{const rootReply=document.querySelector('#messages [data-thread-root="${root.seq}"]'),normalReply=document.querySelector('#messages [data-thread-root="${normal.seq}"]'),actions=normalReply.closest('.reactions');return rootReply.parentElement.classList.contains('reactions')&&actions.getAttribute('aria-label')==='メッセージの操作'&&[...actions.children].slice(0,3).map(el=>el.className).join('|')==='reaction-chip-wrap|reaction-add|btn btn-outline-secondary reply-button'})()`),true);
 assert.equal(await run(`document.querySelector('#messages [data-thread-root="${normal.seq}"]').closest('.reactions').querySelector('.reaction-chip').textContent.trim()`),'1');
 await run("document.querySelector('#messages [data-thread-root]').click()");await wait('T.current?.messages.length===50 && !T.current.loading');
 await run(`handleTypingEvent({type:'typing_start',channelId:'general',threadRootSeq:${root.seq},userId:'bob',typingSession:'bob-thread'})`);
 assert.equal(await run("$('threadTypingStatus').textContent"),'鈴木さんが入力中です…');
 assert.equal(await run("$('typingStatus').textContent"),'');
 await run(`handleTypingEvent({type:'typing_start',channelId:'general',threadRootSeq:${normal.seq},userId:'bob',typingSession:'bob-thread'})`);
 assert.equal(await run("$('threadTypingStatus').textContent"),'');
 await run("handleTypingEvent({type:'typing_start',channelId:'general',userId:'bob',typingSession:'bob-thread'})");
 assert.equal(await run("$('typingStatus').textContent"),'鈴木さんが入力中です…');
 assert.equal(await run("$('threadTypingStatus').textContent"),'');
 await run("handleTypingEvent({type:'typing_stop',channelId:'general',userId:'bob',typingSession:'bob-thread'})");
 assert.equal(await run("$('typingStatus').textContent"),'');
 assert.equal(await run("Math.abs(($('threadStatus').getBoundingClientRect().top+$('threadStatus').getBoundingClientRect().height/2)-($('threadReadAll').getBoundingClientRect().top+$('threadReadAll').getBoundingClientRect().height/2))<1 && $('threadReadAll').textContent.trim()==='スレッドを既読にする' && $('threadReadAll').classList.contains('mark-read-button')"),true);
 assert.equal(await run("$('threadRoot').firstElementChild.textContent==='元のメッセージ' && $('threadRoot').querySelector('.message')!==null"),true);
 await run("$('threadMessages').scrollTop=0");
 await send('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(path.join(temp,'thread-panel-layout.png'),Buffer.from(r.result.data,'base64')));
 assert.equal(await run('T.current.messages[0].seq'),2);
 assert.equal(await run("document.querySelectorAll('#threadReplies img').length"),0,'XSS rendered image');
 await run("document.querySelector('#threadInput').value='下書き';document.querySelector('#threadInput').dispatchEvent(new Event('input'));closeThread();");
 await run(`openThread('general',${root.seq})`);assert.equal(await run("document.querySelector('#threadInput').value"),'下書き');
 // Jump into a later page: automatic read must not skip unseen early replies.
 await run(`openThread('general',${root.seq},60)`);await pause(900);
 const state=await api(admin,`/api/channels/general/threads/${root.seq}/messages?around=60`);
 assert.ok(state.summary.lastReadSeq<40,'jump cleared unseen replies');
 await run("globalThis.threadTestNotices=[];globalThis.threadOriginalNote=note;note=(...args)=>{threadTestNotices.push(args[0]);return threadOriginalNote(...args)}");
 const own=await api(admin,`/api/channels/general/threads/${root.seq}/messages`,'POST',{text:'自分の返信は通知しない'});
 await wait(`T.summaries.get('general:${root.seq}')?.latestSeq===${own.seq} && !T.syncing`);
 assert.equal(await run("threadTestNotices.filter(s=>s.includes('参加中スレッドに新しい返信')).length"),0,'own reply raised notification');
 await run("note=threadOriginalNote;document.querySelector('#threadReadAll').click()");await wait('T.current.summary.unreadCount===0');
 assert.equal((await api(admin,'/api/channels/general/read')).unreadCount,1,'thread read cleared channel');
 assert.equal((await api(admin,'/api/mentions')).unreadCount,1,'thread read cleared mention');
 await run("document.querySelector('#threadInput').value='了解しました';document.querySelector('#threadForm').requestSubmit()");await wait("T.current.messages.some(m=>m.text==='了解しました') && !T.current.sending");
 assert.equal((await api(admin,'/api/channels/general/messages')).messages.length,2,'reply appeared in channel');
 // A failed post must retain the text and target; a failed channel switch must retain the main draft.
 await run(`globalThis.threadTestAPI=api;api=async function(url,options={}){if(url.includes('/threads/')&&options.method==='POST')throw Error('送信失敗テスト');return threadTestAPI(url,options);};document.querySelector('#threadInput').value='失敗時の下書き';document.querySelector('#threadForm').requestSubmit()`);
 await wait("!T.current.sending && document.querySelector('#threadStatus').textContent.includes('送信失敗テスト')");
 assert.equal(await run("document.querySelector('#threadInput').value"),'失敗時の下書き');
 assert.equal(await run('T.current.root'),root.seq);
 await run("api=threadTestAPI;document.querySelector('#input').value='本流の下書き';select('does-not-exist')");
 assert.equal(await run("document.querySelector('#input').value"),'本流の下書き');
 assert.equal(await run('S.channel.id'),'general');
 await run("document.querySelector('#threadInput').value='';document.querySelector('#threadInput').dispatchEvent(new Event('input'))");
 await send('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(path.join(temp,'desktop.png'),Buffer.from(r.result.data,'base64')));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
 await pause(250);
 assert.equal(await run("Math.round(document.querySelector('#threadPanel').getBoundingClientRect().width)"),390);
 assert.equal(await run("document.querySelector('#threadPanel').scrollWidth<=document.querySelector('#threadPanel').clientWidth"),true);
 await send('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(path.join(temp,'mobile.png'),Buffer.from(r.result.data,'base64')));
 await run('closeThread()');const before=requests.filter(p=>/\/threads\/\d+\/messages/.test(p)).length;
 assert.equal(await run("$('channelNav').inert && $('channelNavOpen').getAttribute('aria-expanded') === 'false'"),true);
 await run("$('channelNavOpen').click()");
 await wait("$('channelNavClose') === document.activeElement");
 await pause(220);
 assert.equal(await run("Math.round($('channelNav').getBoundingClientRect().left) === 0"),true,'channel navigation slides fully into view');
 await send('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(path.join(temp,'channel-nav-mobile.png'),Buffer.from(r.result.data,'base64')));
 assert.equal(await run("!$('channelNav').inert"),true,'channel navigation is interactive');
 assert.equal(await run("$('channelNav').getAttribute('aria-modal') === 'true'"),true,'channel navigation is a dialog');
 assert.equal(await run("$('channelNavClose') === document.activeElement"),true,'channel navigation receives focus');
 await run("document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
 assert.equal(await run("$('channelNav').inert && $('channelNavOpen') === document.activeElement"),true);
 await run("$('channelNavOpen').click()");
 await wait("$('channelNavClose') === document.activeElement");
 await send('Emulation.setDeviceMetricsOverride',{width:768,height:844,deviceScaleFactor:1,mobile:false});
 await wait("!$('channelNav').inert && document.activeElement?.classList.contains('channel')");
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
 await wait("$('channelNav').inert && $('channelNavOpen') === document.activeElement");
 await run("$('channelNavOpen').click();document.querySelector('[data-channel-id=other]').click()");
 await wait("S.channel?.id === 'other' && !$('channelNavOpen').getAttribute('aria-expanded').includes('true')");
 await run("$('channelNavOpen').click();document.querySelector('[data-channel-id=general]').click()");
 await wait("S.channel?.id === 'general' && !S.initialLoading");
 assert.equal(await run("$('channelNav').inert && $('title') === document.activeElement && document.documentElement.scrollWidth <= innerWidth"),true);
 for (const width of [1024, 768, 390, 320, 390]) {
  await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:false});
  await pause(220);
  assert.equal(await run("document.documentElement.scrollWidth <= innerWidth && $('send').getBoundingClientRect().right <= innerWidth && !$('channelNav').inert === (innerWidth > 720)"),true,`chat layout at ${width}px`);
 }
 await send('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(path.join(temp,'chat-mobile.png'),Buffer.from(r.result.data,'base64')));
 assert.equal(await run("[...document.querySelectorAll('#messages .reactions')].every(row=>row.scrollWidth<=row.clientWidth)"),true);
 const fresh=await api(bob,`/api/channels/general/threads/${root.seq}/messages`,'POST',{text:'新着返信'});
 await api(bob,`/api/channels/general/threads/${normal.seq}/messages`,'POST',{text:'別件の返信'});
 await wait(`T.summaries.get('general:${root.seq}')?.latestSeq===${fresh.seq}`);
 assert.equal(requests.filter(p=>/\/threads\/\d+\/messages/.test(p)).length,before,'closed realtime fetched bodies');
 await run("$('notifications').click();$('threadTab').click()");
 await wait("T.listChannel === '' && document.querySelectorAll('#threadList .thread-list-row').length===1");
 assert.equal(await run("$('threadScopeAll').getAttribute('aria-pressed') === 'true' && $('threadScopeChannel').textContent.includes('全社連絡')"),true);
 await run("$('threadScopeChannel').click()");
 await wait("T.listChannel === 'general' && document.querySelectorAll('#threadList .thread-list-row').length===2");
 assert.equal(await run("$('threadScopeChannel').getAttribute('aria-pressed') === 'true' && $('threadScope').scrollWidth <= $('threadScope').clientWidth && document.documentElement.scrollWidth <= innerWidth"),true);
 await run("globalThis.threadListAPI=api;api=async(url,options)=>{if(url.startsWith('/api/channels/general/threads?')){if(url.includes('cursor=next'))return {threads:[],nextCursor:''};const page=await threadListAPI(url,options);return {...page,nextCursor:'next'};}return threadListAPI(url,options)};$('threadScopeChannel').click()");
 await wait("T.listChannel === 'general' && !$('moreThreads').classList.contains('hidden')");
 await run("$('moreThreads').click()");
 await wait("T.listChannel === 'general' && T.listCursor === '' && document.querySelectorAll('#threadList .thread-list-row').length === 2");
 await run("api=async(url,options)=>{if(url.startsWith('/api/channels/general/threads?'))throw Error('一覧失敗テスト');return threadListAPI(url,options)};$('threadScopeChannel').click()");
 await wait("$('threadList').textContent.includes('一覧失敗テスト') && !!$('threadList').querySelector('button')");
 await run("api=threadListAPI;document.querySelector('#threadList button').click()");
 await wait("T.listChannel === 'general' && document.querySelectorAll('#threadList .thread-list-row').length === 2");
 await run("syncThreads(false)");
 await wait("!T.syncing && T.listChannel === 'general' && document.querySelectorAll('#threadList .thread-list-row').length === 2");
 await run("$('threadScopeAll').click()");
 await wait("T.listChannel === '' && document.querySelectorAll('#threadList .thread-list-row').length===1");
 await run("document.querySelector('#threadList .thread-list-row').click()");await wait('T.current && !T.current.loading');
 // Reconnect must recover a missed update, while a closed thread still stays lazy.
 await run('closeThread(); S.ws.onclose=null; S.ws.close()');await pause(100);
 const missed=await api(bob,`/api/channels/general/threads/${root.seq}/messages`,'POST',{text:'切断中の返信'});
 await run('realtime()');await wait(`T.summaries.get('general:${root.seq}')?.latestSeq===${missed.seq}`);
 await run(`openThread('general',${root.seq},${missed.seq})`);assert.equal(await run(`T.current.messages.some(m=>m.seq===${missed.seq})`),true);

 // The compact reply composer preserves rich text through drafts and posting.
 const rich='**太字** __下線__ ~~取消~~\n> 引用\n[リンク](https://example.com/path)';
 await run(`$('threadInput').value=${JSON.stringify(rich)};$('threadInput').dispatchEvent(new Event('input',{bubbles:true}))`);
 assert.equal(await run("!!$('threadInput').querySelector('strong, b') && !!$('threadInput').querySelector('u') && !!$('threadInput').querySelector('s') && !!$('threadInput').querySelector('blockquote') && !!$('threadInput').querySelector('a')"),true);
 assert.equal(await run("$('threadInput').value"),rich);
 await run('closeThread()');await run(`openThread('general',${root.seq})`);
 assert.equal(await run("$('threadInput').value"),rich);
 assert.equal(await run("!!$('threadInput').querySelector('blockquote')"),true);
 await run("$('threadForm').requestSubmit()");await wait(`T.current.messages.some(m=>m.text===${JSON.stringify(rich)}) && !T.current.sending`);
 assert.equal(await run(`(()=>{const row=[...$('threadReplies').querySelectorAll('.message')].find(row=>row.textContent.includes('太字'));return !!row?.querySelector('strong')&&!!row?.querySelector('blockquote')&&!!row?.querySelector('a')})()`),true);
 await run("(()=>{$('threadInput').value='書式';$('threadInput').focus();const range=document.createRange();range.selectNodeContents($('threadInput'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.querySelector('.thread-tools [data-format=bold]').click()})()");
 assert.equal(await run("$('threadInput').value"),'**書式**');
 await run("(()=>{$('threadInput').value='リンク文字';$('threadInput').focus();const range=document.createRange();range.selectNodeContents($('threadInput'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);$('threadLinkButton').click()})()");
 await wait("$('linkModal').classList.contains('show')");
 await pause(350);
 await run("$('linkURL').value='https://intranet.example/page';$('linkForm').requestSubmit()");await wait("!$('linkModal').classList.contains('show')");
 assert.equal(await run("$('threadInput').value"),'[リンク文字](https://intranet.example/page)');
 await run("$('threadInput').value='a'.repeat(16385)");
 assert.equal(await run("$('threadSend').disabled && $('threadEditorLimit').textContent.includes('16,385')"),true);
 await run("(()=>{$('threadInput').value='';$('threadInput').focus();const data=new DataTransfer();data.setData('text/plain','貼り付け');data.setData('text/html','<img src=x onerror=alert(1)>');$('threadInput').dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))})()");
 assert.equal(await run("$('threadInput').value==='貼り付け' && !$('threadInput').querySelector('img')"),true);
 await run("$('threadInput').value=''");

 // Participant picker: real insertion/undo, notification, async isolation and IME.
 await run(`globalThis.setThreadValue=(value,offset=value.length)=>{const input=$('threadInput');input.value=value;input.focus();const node=input.firstChild||input;const range=document.createRange();range.setStart(node,Math.min(offset,node.nodeValue?.length||0));range.collapse(true);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);input.dispatchEvent(new Event('input',{bubbles:true}))};setThreadValue('前 後',2);$('threadMentionButton').click()`);
 await wait('threadMention && !threadMention.loading');
 assert.deepEqual(await run('threadMention.matches.map(u=>u.id)'),['bob']);
 await run("$('threadMentionSearch').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',ctrlKey:true,bubbles:true,cancelable:true}))");
 assert.equal(await run("$('threadInput').value"),'前 後');
 await run("$('threadMentionSearch').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))");
 assert.equal(await run("$('threadInput').value"),'前 @bob（鈴木） 後');
 await run("document.execCommand('undo')");
 assert.equal(await run("$('threadInput').value"),'前 後');
 await run("document.execCommand('redo')");
 assert.equal(await run("$('threadInput').value"),'前 @bob（鈴木） 後');
 await run("$('threadForm').requestSubmit()");
 await wait("T.current.messages.some(m=>m.text==='前 @bob（鈴木） 後') && !T.current.sending");
 assert.ok((await api(bob,'/api/mentions')).unreadCount>0,'selected participant was not notified');
 await run("setThreadValue('mail@example.com')");
 assert.equal(await run('threadMention===null'),true);
 await run("setThreadValue('@鈴')");
 await wait('threadMention && !threadMention.loading');
 const detailRequests=requests.filter(u=>u===base+'/api/channels/general').length;
 await run("setThreadValue('@鈴木')");
 assert.equal(requests.filter(u=>u===base+'/api/channels/general').length,detailRequests);
 await run("$('threadInput').dispatchEvent(new CompositionEvent('compositionstart'));$('threadInput').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',ctrlKey:true,isComposing:true,bubbles:true,cancelable:true}))");
 assert.equal(await run("$('threadInput').value"),'@鈴木');
 await run("$('threadInput').dispatchEvent(new CompositionEvent('compositionend'))");await pause(120);
 await run("$('threadInput').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))");
 assert.equal(await run("$('threadInput').value"),'@bob（鈴木） ');
 await run("$('threadMentionButton').click()");await wait('threadMention && !threadMention.loading');
 await run("$('threadMentionSearch').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}))");
 assert.equal(await run('!!T.current && threadMention===null'),true);
 // No stale choices on failure, and retry leaves the draft intact.
 await run("globalThis.pickerAPI=api;api=async(url,opts)=>{if(url==='/api/channels/general')throw Error('取得失敗テスト');return pickerAPI(url,opts)};$('threadMentionButton').click()");
 await wait('!!threadMention?.error');
 assert.equal(await run('threadMention.matches.length'),0);
 await run("api=pickerAPI;$('threadMentionRetry').click()");await wait('threadMention && !threadMention.loading && !threadMention.error');
 assert.equal(await run("$('threadInput').value"),'@bob（鈴木） ');
 await run("(async()=>{closeThreadMention();globalThis.pickerChannel=await api('/api/channels/general');api=(url,opts)=>url==='/api/channels/general'?new Promise(resolve=>globalThis.resolvePicker=resolve):pickerAPI(url,opts);$('threadMentionButton').click()})()");
 await wait("typeof resolvePicker==='function'");
 await run(`openThread('general',${normal.seq})`);
 await run('resolvePicker(pickerChannel);api=pickerAPI');await pause(50);
 assert.equal(await run('threadMention===null'),true);
 assert.equal(await run("$('threadInput').value"),'');
 // Candidate policy and 500-person menu use API fixtures without creating 500 accounts.
 assert.deepEqual(await run("channelMentionCandidates({effectiveMembers:[{id:S.me.id,name:'自分'},{id:'off',name:'無効',enabled:false},{id:'b',name:'同名'},{id:'a',name:'同名'},{id:'a',name:'同名'}]}).map(u=>u.id)"),['a','b']);
 await run("api=async(url,opts)=>url==='/api/channels/general'?{...pickerChannel,effectiveMembers:Array.from({length:500},(_,i)=>({id:'u'+i,name:i===0?'特殊<img>） @admin\\n表示':'参加者'+String(i).padStart(3,'0')}))}:pickerAPI(url,opts);$('threadMentionButton').click()");
 await wait('threadMention?.matches.length===500');
 assert.equal(await run("!!$('threadMentionOptions').querySelector('.mention-option .mini') && getComputedStyle($('threadMentionOptions').querySelector('[aria-selected=true]')).boxShadow==='none'"),true);
 assert.equal(await run("$('threadMentionOptions').querySelectorAll('img').length"),0);
 assert.equal(await run("$('threadMentionOptions').scrollHeight>$('threadMentionOptions').clientHeight"),true);
 assert.equal(await run("$('threadMentionMenu').getBoundingClientRect().left>=0 && $('threadMentionMenu').getBoundingClientRect().right<=innerWidth"),true);
 await send('Page.captureScreenshot',{format:'png'}).then(r=>fs.writeFileSync(path.join(temp,'mention-mobile.png'),Buffer.from(r.result.data,'base64')));
 await run("$('threadMentionSearch').value='特殊';$('threadMentionSearch').dispatchEvent(new Event('input'));document.querySelector('#threadMentionOptions button').click()");
 assert.equal(await run("$('threadInput').value.includes('＠admin') && !$('threadInput').value.includes('@admin')"),true);
 await run('api=pickerAPI');
 // Group-derived members are selectable, and the shared main editor still inserts chips.
 await api(admin,'/api/groups','POST',{id:'team',name:'開発'});
 await api(admin,'/api/users','POST',{users:[{id:'group-user',name:'グループ参加者',password,role:'user',groups:['team']}]});
 await api(admin,'/api/channels','POST',{id:'group-room',name:'グループ部屋',type:'public',groups:['team']});
 const groupRoot=await api(admin,'/api/channels/group-room/messages','POST',{text:'グループの相談'});
 await run("closeThread();select('group-room')");await wait("S.channel?.id==='group-room'");
 await run(`openThread('group-room',${groupRoot.seq})`);
 await run("$('threadMentionButton').click()");await wait('threadMention && !threadMention.loading');
 assert.deepEqual(await run('threadMention.matches.map(u=>u.id)'),['group-user']);
 await run("closeThread();$('input').value='';editor.focus();$('mentionButton').click();$('mentionSearch').value='グループ参加者';$('mentionSearch').dispatchEvent(new Event('input'))");
 await pause(50);
 await run("document.querySelector('#mentionOptions button').click()");
 assert.equal(await run("$('input').value.includes('@group-user（グループ参加者）')"),true);
 assert.equal(errors.length,0,JSON.stringify(errors));
 console.log('PASS: real HTTP + WebSocket, notification clear, thread typing scope, lazy bodies, 60-reply paging, unread isolation, draft/failure recovery, XSS, desktop/mobile, updates and reconnect, participant picker/undo/IME/failures/500 candidates/group membership');
 console.log('Screenshots:',temp);
}finally{cdp?.close();chrome?.kill();app.kill();}
